Page/Main Page/Controllers/ShoppingCartController.cs
using DAL.Interfaces;
using Main_Page.Service;
using Main_Page.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Main_Page.Controllers
{
    public class ShoppingCartController : BaseController
    {

        private readonly IUOW _uow;

        public ShoppingCartController(IUOW uow)
        {
            _uow = uow;
        }

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext, _uow);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {

            var addedAlbum = _uow.Albums.GetById(id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext, _uow);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext, _uow);
            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

             // Get the name of the album to display confirmation

            //string albumName = _uow.Cart..Album.Title;
            //string albumName = ShoppingCart.Carts.Single(item => item.AlbumId == id).Album.Title;
            

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {

                Message = Server.HtmlEncode("sdasd") +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext, _uow);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

Page/Main Page/Controllers/StoreController.cs
using DAL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;


namespace Main_Page.Controllers
{
    public class StoreController : BaseController
    {
        // GET: Store

        private readonly IUOW _uow;

        public StoreController(IUOW uow)
        {
            _uow = uow;
        }

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var genres = _uow.Genres.All;
            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            //var genreModel = storeDB.Genres.Include("Albums")
            //    .Single(g => g.Name == genre);

            var genreModel = _uow.Genre.GetGenreWithAlbums(genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5
        public ActionResult Details(int id)
        {
            var album = _uow.Albums.GetById(id);
            return View(album);
        }

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = _uow.Genres.All;
            return PartialView(genres);
        }
    }
}

Page/Main Page/Views/Shared/_Layout.cshtml
@using System.Threading
@{
    var titleTag = Resources.Common.ApplicationName;

    // set up global js variable, to hold culture code
    // it is later used for globalize, cldr and moment
    var currentCultureCode = "root";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    switch (Thread.CurrentThread.CurrentCulture.ToString())
    {
        case "et-EE":
            currentCultureCode = "et";
            break;
        case "en-US":
            currentCultureCode = "en";
            break;
        default:
            currentCultureCode = Thread.CurrentThread.CurrentCulture.ToString();
            break;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@titleTag</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-2.2.3.js" type="text/javascript"></script>
    <script type="text/javascript">
        var currentCultureCode = '@currentCultureCode';
    </script>
    @RenderSection("headerscripts", required: false)
</head>
<body>
    <div id="header">
        <h1><a href="/">@Resources.Common.ApplicationNameCapital</a></h1>
        <a class="eesti" href="#"><img alt="eesti" src="~/Content/Images/ee.png"></a>
        <a class="english" href="#"><img alt="enUS" src="~/Content/Images/us.png"></a>
        <ul id="navlist">
            <li class="first"><a href="@Url.Content("~")" id="current">@Resources.Common.Home</a></li>
            <li><a href="@Url.Content("~/Store/")">@Resources.Common.Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li><a href="@Url.Content("~/StoreManager/")">@Resources.Common.Admin</a></li>
        </ul>
    </div>
    @{Html.RenderAction("GenreMenu", "Store");}
    <div id="main">
        @RenderBody()
    </div>

            <div id="footer">
                <p>
                    &copy; @DateTime.Now.Year - @Resources.Common.ApplicationName
                    (Culture:<b>@Culture</b> UICulture:<b>@UICulture</b>)
                </p>
            </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/cldr")
        @Scripts.Render("~/bundles/globalize")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/moment")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/tinymce/tinymce.min.js")
        @Scripts.Render("~/bundles/app")

        @RenderSection("scripts", required: false)
    </body>
</html>
<script type="text/javascript">
    $(function () {
        $(".eesti").click(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("SetCulture", "Home")",
                data: {
                    culture:"et-EE"
                },
                success: function () {
                    window.location.reload(true);
                }
        });
        });

        $(".english").click(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("SetCulture", "Home")",
                data: {
                culture:"en-US"
                },
                success: function() {
                    window.location.reload(true);
                }
        });
    });
    });
</script>